[project]
name = "SimBLEND"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hydra-core>=1.3.2",
    "ipyparallel>=9.0.1",
    "jupyterlab>=4.3.6",
    "lightning>=2.5.1",
    "nbdime>=4.0.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "pytorch-metric-learning>=2.8.1",
    "retrying>=1.3.4",
    "rich>=13.9.4",
    "rootutils>=1.0.7",
    "wandb>=0.19.8",
]
